/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'title' : string,
  'availableCopies' : bigint,
  'isbn' : string,
  'publisher' : string,
  'year' : bigint,
  'author' : string,
  'totalCopies' : bigint,
  'ddcNumber' : string,
  'department' : string,
  'location' : Location,
}
export interface Circulation {
  'issueDate' : Time,
  'status' : CirculationStatus,
  'borrowerId' : string,
  'dueDate' : Time,
  'renewalCount' : bigint,
  'bookId' : string,
  'returnDate' : [] | [Time],
}
export type CirculationStatus = { 'lost' : null } |
  { 'reserved' : null } |
  { 'available' : null } |
  { 'issued' : null } |
  { 'renewed' : null } |
  { 'returned' : null };
export interface EResource {
  'title' : string,
  'resourceType' : string,
  'department' : string,
  'uploadDate' : Time,
  'uploadedBy' : string,
  'fileUrl' : string,
}
export interface Fine {
  'circulationId' : string,
  'userId' : string,
  'paid' : boolean,
  'paymentDate' : [] | [Time],
  'amount' : bigint,
  'reason' : string,
}
export interface GateEntry {
  'exitTime' : [] | [Time],
  'entryTime' : Time,
  'userId' : string,
  'mobileNumber' : string,
}
export interface Journal {
  'title' : string,
  'subscriptionCost' : bigint,
  'arrivedThisMonth' : boolean,
  'journalType' : { 'Print' : null } |
    { 'EJournal' : null },
  'frequency' : string,
  'department' : string,
}
export type LibraryRole = { 'Staff' : null } |
  { 'Student' : null } |
  { 'Admin' : null } |
  { 'Librarian' : null };
export interface Location {
  'floor' : bigint,
  'hallName' : string,
  'shelfNumber' : string,
  'rackNumber' : string,
}
export interface Magazine {
  'title' : string,
  'purchaseDate' : Time,
  'cost' : bigint,
  'subscriptionPeriod' : bigint,
  'department' : string,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'password' : string,
  'role' : LibraryRole,
  'year' : bigint,
  'approved' : boolean,
  'department' : string,
  'phoneNumber' : string,
  'registerId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      string,
    ],
    undefined
  >,
  'addEResource' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addJournal' : ActorMethod<
    [
      string,
      string,
      { 'Print' : null } |
        { 'EJournal' : null },
      bigint,
      string,
      string,
      boolean,
    ],
    undefined
  >,
  'addMagazine' : ActorMethod<
    [string, string, Time, bigint, bigint, string],
    undefined
  >,
  'approveRegistration' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllEResources' : ActorMethod<[], Array<EResource>>,
  'getAllJournals' : ActorMethod<[], Array<Journal>>,
  'getAllMagazines' : ActorMethod<[], Array<Magazine>>,
  'getBook' : ActorMethod<[string], Book>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyGateLog' : ActorMethod<[], Array<GateEntry>>,
  'getOverdueBooks' : ActorMethod<[], Array<Circulation>>,
  'getUserBorrowedBooks' : ActorMethod<[string], Array<Circulation>>,
  'getUserFines' : ActorMethod<[string], Array<Fine>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueBook' : ActorMethod<[string, string, string], undefined>,
  'logEntry' : ActorMethod<[string, string, string], undefined>,
  'logExit' : ActorMethod<[string], undefined>,
  'payFine' : ActorMethod<[string, Time], undefined>,
  'rejectRegistration' : ActorMethod<[string], undefined>,
  'renewBook' : ActorMethod<[string], undefined>,
  'returnBook' : ActorMethod<[string, Time], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBooks' : ActorMethod<[string], Array<Book>>,
  'submitRegistrationRequest' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
  'updateBook' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];