/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({
  'floor' : IDL.Nat,
  'hallName' : IDL.Text,
  'shelfNumber' : IDL.Text,
  'rackNumber' : IDL.Text,
});
export const Book = IDL.Record({
  'title' : IDL.Text,
  'availableCopies' : IDL.Nat,
  'isbn' : IDL.Text,
  'publisher' : IDL.Text,
  'year' : IDL.Nat,
  'author' : IDL.Text,
  'totalCopies' : IDL.Nat,
  'ddcNumber' : IDL.Text,
  'department' : IDL.Text,
  'location' : Location,
});
export const EResource = IDL.Record({
  'title' : IDL.Text,
  'resourceType' : IDL.Text,
  'department' : IDL.Text,
  'uploadDate' : Time,
  'uploadedBy' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const Journal = IDL.Record({
  'title' : IDL.Text,
  'subscriptionCost' : IDL.Nat,
  'arrivedThisMonth' : IDL.Bool,
  'journalType' : IDL.Variant({ 'Print' : IDL.Null, 'EJournal' : IDL.Null }),
  'frequency' : IDL.Text,
  'department' : IDL.Text,
});
export const Magazine = IDL.Record({
  'title' : IDL.Text,
  'purchaseDate' : Time,
  'cost' : IDL.Nat,
  'subscriptionPeriod' : IDL.Nat,
  'department' : IDL.Text,
});
export const LibraryRole = IDL.Variant({
  'Staff' : IDL.Null,
  'Student' : IDL.Null,
  'Admin' : IDL.Null,
  'Librarian' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : LibraryRole,
  'year' : IDL.Nat,
  'approved' : IDL.Bool,
  'department' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'registerId' : IDL.Text,
});
export const GateEntry = IDL.Record({
  'exitTime' : IDL.Opt(Time),
  'entryTime' : Time,
  'userId' : IDL.Text,
  'mobileNumber' : IDL.Text,
});
export const CirculationStatus = IDL.Variant({
  'lost' : IDL.Null,
  'reserved' : IDL.Null,
  'available' : IDL.Null,
  'issued' : IDL.Null,
  'renewed' : IDL.Null,
  'returned' : IDL.Null,
});
export const Circulation = IDL.Record({
  'issueDate' : Time,
  'status' : CirculationStatus,
  'borrowerId' : IDL.Text,
  'dueDate' : Time,
  'renewalCount' : IDL.Nat,
  'bookId' : IDL.Text,
  'returnDate' : IDL.Opt(Time),
});
export const Fine = IDL.Record({
  'circulationId' : IDL.Text,
  'userId' : IDL.Text,
  'paid' : IDL.Bool,
  'paymentDate' : IDL.Opt(Time),
  'amount' : IDL.Nat,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addEResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addJournal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'Print' : IDL.Null, 'EJournal' : IDL.Null }),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'addMagazine' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'approveRegistration' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllEResources' : IDL.Func([], [IDL.Vec(EResource)], ['query']),
  'getAllJournals' : IDL.Func([], [IDL.Vec(Journal)], ['query']),
  'getAllMagazines' : IDL.Func([], [IDL.Vec(Magazine)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyGateLog' : IDL.Func([], [IDL.Vec(GateEntry)], ['query']),
  'getOverdueBooks' : IDL.Func([], [IDL.Vec(Circulation)], ['query']),
  'getUserBorrowedBooks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Circulation)],
      ['query'],
    ),
  'getUserFines' : IDL.Func([IDL.Text], [IDL.Vec(Fine)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'logEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'logExit' : IDL.Func([IDL.Text], [], []),
  'payFine' : IDL.Func([IDL.Text, Time], [], []),
  'rejectRegistration' : IDL.Func([IDL.Text], [], []),
  'renewBook' : IDL.Func([IDL.Text], [], []),
  'returnBook' : IDL.Func([IDL.Text, Time], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'submitRegistrationRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateBook' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({
    'floor' : IDL.Nat,
    'hallName' : IDL.Text,
    'shelfNumber' : IDL.Text,
    'rackNumber' : IDL.Text,
  });
  const Book = IDL.Record({
    'title' : IDL.Text,
    'availableCopies' : IDL.Nat,
    'isbn' : IDL.Text,
    'publisher' : IDL.Text,
    'year' : IDL.Nat,
    'author' : IDL.Text,
    'totalCopies' : IDL.Nat,
    'ddcNumber' : IDL.Text,
    'department' : IDL.Text,
    'location' : Location,
  });
  const EResource = IDL.Record({
    'title' : IDL.Text,
    'resourceType' : IDL.Text,
    'department' : IDL.Text,
    'uploadDate' : Time,
    'uploadedBy' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const Journal = IDL.Record({
    'title' : IDL.Text,
    'subscriptionCost' : IDL.Nat,
    'arrivedThisMonth' : IDL.Bool,
    'journalType' : IDL.Variant({ 'Print' : IDL.Null, 'EJournal' : IDL.Null }),
    'frequency' : IDL.Text,
    'department' : IDL.Text,
  });
  const Magazine = IDL.Record({
    'title' : IDL.Text,
    'purchaseDate' : Time,
    'cost' : IDL.Nat,
    'subscriptionPeriod' : IDL.Nat,
    'department' : IDL.Text,
  });
  const LibraryRole = IDL.Variant({
    'Staff' : IDL.Null,
    'Student' : IDL.Null,
    'Admin' : IDL.Null,
    'Librarian' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : LibraryRole,
    'year' : IDL.Nat,
    'approved' : IDL.Bool,
    'department' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'registerId' : IDL.Text,
  });
  const GateEntry = IDL.Record({
    'exitTime' : IDL.Opt(Time),
    'entryTime' : Time,
    'userId' : IDL.Text,
    'mobileNumber' : IDL.Text,
  });
  const CirculationStatus = IDL.Variant({
    'lost' : IDL.Null,
    'reserved' : IDL.Null,
    'available' : IDL.Null,
    'issued' : IDL.Null,
    'renewed' : IDL.Null,
    'returned' : IDL.Null,
  });
  const Circulation = IDL.Record({
    'issueDate' : Time,
    'status' : CirculationStatus,
    'borrowerId' : IDL.Text,
    'dueDate' : Time,
    'renewalCount' : IDL.Nat,
    'bookId' : IDL.Text,
    'returnDate' : IDL.Opt(Time),
  });
  const Fine = IDL.Record({
    'circulationId' : IDL.Text,
    'userId' : IDL.Text,
    'paid' : IDL.Bool,
    'paymentDate' : IDL.Opt(Time),
    'amount' : IDL.Nat,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addEResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addJournal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'Print' : IDL.Null, 'EJournal' : IDL.Null }),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'addMagazine' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'approveRegistration' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllEResources' : IDL.Func([], [IDL.Vec(EResource)], ['query']),
    'getAllJournals' : IDL.Func([], [IDL.Vec(Journal)], ['query']),
    'getAllMagazines' : IDL.Func([], [IDL.Vec(Magazine)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyGateLog' : IDL.Func([], [IDL.Vec(GateEntry)], ['query']),
    'getOverdueBooks' : IDL.Func([], [IDL.Vec(Circulation)], ['query']),
    'getUserBorrowedBooks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Circulation)],
        ['query'],
      ),
    'getUserFines' : IDL.Func([IDL.Text], [IDL.Vec(Fine)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'logEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'logExit' : IDL.Func([IDL.Text], [], []),
    'payFine' : IDL.Func([IDL.Text, Time], [], []),
    'rejectRegistration' : IDL.Func([IDL.Text], [], []),
    'renewBook' : IDL.Func([IDL.Text], [], []),
    'returnBook' : IDL.Func([IDL.Text, Time], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'submitRegistrationRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateBook' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };