/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    floor: bigint;
    hallName: string;
    shelfNumber: string;
    rackNumber: string;
}
export type Time = bigint;
export interface Journal {
    title: string;
    subscriptionCost: bigint;
    arrivedThisMonth: boolean;
    journalType: Variant_Print_EJournal;
    frequency: string;
    department: string;
}
export interface Fine {
    circulationId: string;
    userId: string;
    paid: boolean;
    paymentDate?: Time;
    amount: bigint;
    reason: string;
}
export interface GateEntry {
    exitTime?: Time;
    entryTime: Time;
    userId: string;
    mobileNumber: string;
}
export interface Magazine {
    title: string;
    purchaseDate: Time;
    cost: bigint;
    subscriptionPeriod: bigint;
    department: string;
}
export interface Book {
    title: string;
    availableCopies: bigint;
    isbn: string;
    publisher: string;
    year: bigint;
    author: string;
    totalCopies: bigint;
    ddcNumber: string;
    department: string;
    location: Location;
}
export interface Circulation {
    issueDate: Time;
    status: CirculationStatus;
    borrowerId: string;
    dueDate: Time;
    renewalCount: bigint;
    bookId: string;
    returnDate?: Time;
}
export interface UserProfile {
    username: string;
    password: string;
    role: LibraryRole;
    year: bigint;
    approved: boolean;
    department: string;
    phoneNumber: string;
    registerId: string;
}
export interface EResource {
    title: string;
    resourceType: string;
    department: string;
    uploadDate: Time;
    uploadedBy: string;
    fileUrl: string;
}
export enum CirculationStatus {
    lost = "lost",
    reserved = "reserved",
    available = "available",
    issued = "issued",
    renewed = "renewed",
    returned = "returned"
}
export enum LibraryRole {
    Staff = "Staff",
    Student = "Student",
    Admin = "Admin",
    Librarian = "Librarian"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Print_EJournal {
    Print = "Print",
    EJournal = "EJournal"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBook(bookId: string, title: string, author: string, isbn: string, publisher: string, year: bigint, department: string, ddcNumber: string, totalCopies: bigint, floor: bigint, hallName: string, rackNumber: string, shelfNumber: string): Promise<void>;
    addEResource(resourceId: string, title: string, resourceType: string, department: string, fileUrl: string): Promise<void>;
    addJournal(journalId: string, title: string, journalType: Variant_Print_EJournal, subscriptionCost: bigint, frequency: string, department: string, arrivedThisMonth: boolean): Promise<void>;
    addMagazine(magazineId: string, title: string, purchaseDate: Time, cost: bigint, subscriptionPeriod: bigint, department: string): Promise<void>;
    approveRegistration(registerId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBook(bookId: string): Promise<void>;
    getAllBooks(): Promise<Array<Book>>;
    getAllEResources(): Promise<Array<EResource>>;
    getAllJournals(): Promise<Array<Journal>>;
    getAllMagazines(): Promise<Array<Magazine>>;
    getBook(bookId: string): Promise<Book>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyGateLog(): Promise<Array<GateEntry>>;
    getOverdueBooks(): Promise<Array<Circulation>>;
    getUserBorrowedBooks(userId: string): Promise<Array<Circulation>>;
    getUserFines(userId: string): Promise<Array<Fine>>;
    isCallerAdmin(): Promise<boolean>;
    issueBook(circulationId: string, userId: string, bookId: string): Promise<void>;
    logEntry(entryId: string, userId: string, mobileNumber: string): Promise<void>;
    logExit(entryId: string): Promise<void>;
    payFine(fineId: string, paymentDate: Time): Promise<void>;
    rejectRegistration(registerId: string): Promise<void>;
    renewBook(circulationId: string): Promise<void>;
    returnBook(circulationId: string, returnDate: Time): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchBooks(searchText: string): Promise<Array<Book>>;
    submitRegistrationRequest(registerId: string, username: string, department: string, year: bigint, phoneNumber: string): Promise<void>;
    updateBook(bookId: string, title: string, author: string, isbn: string, publisher: string, year: bigint, department: string, ddcNumber: string, totalCopies: bigint, floor: bigint, hallName: string, rackNumber: string, shelfNumber: string): Promise<void>;
}
import type { Circulation as _Circulation, CirculationStatus as _CirculationStatus, Fine as _Fine, GateEntry as _GateEntry, Journal as _Journal, LibraryRole as _LibraryRole, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBook(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: string, arg8: bigint, arg9: bigint, arg10: string, arg11: string, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
    async addEResource(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEResource(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEResource(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addJournal(arg0: string, arg1: string, arg2: Variant_Print_EJournal, arg3: bigint, arg4: string, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournal(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournal(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addMagazine(arg0: string, arg1: string, arg2: Time, arg3: bigint, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMagazine(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMagazine(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async approveRegistration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRegistration(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async getAllBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooks();
            return result;
        }
    }
    async getAllEResources(): Promise<Array<EResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEResources();
            return result;
        }
    }
    async getAllJournals(): Promise<Array<Journal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournals();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournals();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMagazines(): Promise<Array<Magazine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMagazines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMagazines();
            return result;
        }
    }
    async getBook(arg0: string): Promise<Book> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyGateLog(): Promise<Array<GateEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyGateLog();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyGateLog();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverdueBooks(): Promise<Array<Circulation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueBooks();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueBooks();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBorrowedBooks(arg0: string): Promise<Array<Circulation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBorrowedBooks(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBorrowedBooks(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFines(arg0: string): Promise<Array<Fine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFines(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFines(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async issueBook(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.issueBook(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issueBook(arg0, arg1, arg2);
            return result;
        }
    }
    async logEntry(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async logExit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logExit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logExit(arg0);
            return result;
        }
    }
    async payFine(arg0: string, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.payFine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payFine(arg0, arg1);
            return result;
        }
    }
    async rejectRegistration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRegistration(arg0);
            return result;
        }
    }
    async renewBook(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renewBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renewBook(arg0);
            return result;
        }
    }
    async returnBook(arg0: string, arg1: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.returnBook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnBook(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchBooks(arg0: string): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBooks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBooks(arg0);
            return result;
        }
    }
    async submitRegistrationRequest(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRegistrationRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRegistrationRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateBook(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: string, arg8: bigint, arg9: bigint, arg10: string, arg11: string, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
}
function from_candid_CirculationStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CirculationStatus): CirculationStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Circulation_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Circulation): Circulation {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Fine_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fine): Fine {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_GateEntry_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GateEntry): GateEntry {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Journal_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Journal): Journal {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_LibraryRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LibraryRole): LibraryRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    password: string;
    role: _LibraryRole;
    year: bigint;
    approved: boolean;
    department: string;
    phoneNumber: string;
    registerId: string;
}): {
    username: string;
    password: string;
    role: LibraryRole;
    year: bigint;
    approved: boolean;
    department: string;
    phoneNumber: string;
    registerId: string;
} {
    return {
        username: value.username,
        password: value.password,
        role: from_candid_LibraryRole_n11(_uploadFile, _downloadFile, value.role),
        year: value.year,
        approved: value.approved,
        department: value.department,
        phoneNumber: value.phoneNumber,
        registerId: value.registerId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exitTime: [] | [_Time];
    entryTime: _Time;
    userId: string;
    mobileNumber: string;
}): {
    exitTime?: Time;
    entryTime: Time;
    userId: string;
    mobileNumber: string;
} {
    return {
        exitTime: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.exitTime)),
        entryTime: value.entryTime,
        userId: value.userId,
        mobileNumber: value.mobileNumber
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issueDate: _Time;
    status: _CirculationStatus;
    borrowerId: string;
    dueDate: _Time;
    renewalCount: bigint;
    bookId: string;
    returnDate: [] | [_Time];
}): {
    issueDate: Time;
    status: CirculationStatus;
    borrowerId: string;
    dueDate: Time;
    renewalCount: bigint;
    bookId: string;
    returnDate?: Time;
} {
    return {
        issueDate: value.issueDate,
        status: from_candid_CirculationStatus_n22(_uploadFile, _downloadFile, value.status),
        borrowerId: value.borrowerId,
        dueDate: value.dueDate,
        renewalCount: value.renewalCount,
        bookId: value.bookId,
        returnDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.returnDate))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    circulationId: string;
    userId: string;
    paid: boolean;
    paymentDate: [] | [_Time];
    amount: bigint;
    reason: string;
}): {
    circulationId: string;
    userId: string;
    paid: boolean;
    paymentDate?: Time;
    amount: bigint;
    reason: string;
} {
    return {
        circulationId: value.circulationId,
        userId: value.userId,
        paid: value.paid,
        paymentDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.paymentDate)),
        amount: value.amount,
        reason: value.reason
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    subscriptionCost: bigint;
    arrivedThisMonth: boolean;
    journalType: {
        Print: null;
    } | {
        EJournal: null;
    };
    frequency: string;
    department: string;
}): {
    title: string;
    subscriptionCost: bigint;
    arrivedThisMonth: boolean;
    journalType: Variant_Print_EJournal;
    frequency: string;
    department: string;
} {
    return {
        title: value.title,
        subscriptionCost: value.subscriptionCost,
        arrivedThisMonth: value.arrivedThisMonth,
        journalType: from_candid_variant_n7(_uploadFile, _downloadFile, value.journalType),
        frequency: value.frequency,
        department: value.department
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Staff: null;
} | {
    Student: null;
} | {
    Admin: null;
} | {
    Librarian: null;
}): LibraryRole {
    return "Staff" in value ? LibraryRole.Staff : "Student" in value ? LibraryRole.Student : "Admin" in value ? LibraryRole.Admin : "Librarian" in value ? LibraryRole.Librarian : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lost: null;
} | {
    reserved: null;
} | {
    available: null;
} | {
    issued: null;
} | {
    renewed: null;
} | {
    returned: null;
}): CirculationStatus {
    return "lost" in value ? CirculationStatus.lost : "reserved" in value ? CirculationStatus.reserved : "available" in value ? CirculationStatus.available : "issued" in value ? CirculationStatus.issued : "renewed" in value ? CirculationStatus.renewed : "returned" in value ? CirculationStatus.returned : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Print: null;
} | {
    EJournal: null;
}): Variant_Print_EJournal {
    return "Print" in value ? Variant_Print_EJournal.Print : "EJournal" in value ? Variant_Print_EJournal.EJournal : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GateEntry>): Array<GateEntry> {
    return value.map((x)=>from_candid_GateEntry_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Circulation>): Array<Circulation> {
    return value.map((x)=>from_candid_Circulation_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fine>): Array<Fine> {
    return value.map((x)=>from_candid_Fine_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Journal>): Array<Journal> {
    return value.map((x)=>from_candid_Journal_n5(_uploadFile, _downloadFile, x));
}
function to_candid_LibraryRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LibraryRole): _LibraryRole {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    password: string;
    role: LibraryRole;
    year: bigint;
    approved: boolean;
    department: string;
    phoneNumber: string;
    registerId: string;
}): {
    username: string;
    password: string;
    role: _LibraryRole;
    year: bigint;
    approved: boolean;
    department: string;
    phoneNumber: string;
    registerId: string;
} {
    return {
        username: value.username,
        password: value.password,
        role: to_candid_LibraryRole_n29(_uploadFile, _downloadFile, value.role),
        year: value.year,
        approved: value.approved,
        department: value.department,
        phoneNumber: value.phoneNumber,
        registerId: value.registerId
    };
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Print_EJournal): {
    Print: null;
} | {
    EJournal: null;
} {
    return value == Variant_Print_EJournal.Print ? {
        Print: null
    } : value == Variant_Print_EJournal.EJournal ? {
        EJournal: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LibraryRole): {
    Staff: null;
} | {
    Student: null;
} | {
    Admin: null;
} | {
    Librarian: null;
} {
    return value == LibraryRole.Staff ? {
        Staff: null
    } : value == LibraryRole.Student ? {
        Student: null
    } : value == LibraryRole.Admin ? {
        Admin: null
    } : value == LibraryRole.Librarian ? {
        Librarian: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
